[theme]
primaryColor = "#3DB985"              # Teal
backgroundColor = "#FFFFFF"           # Crisp white background
secondaryBackgroundColor = "#F7F7F7"  # Soft light gray panels
textColor = "#2C2C3C"                 # Deep navy for legibility
font = "sans serif"
